# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: ビルド & テスト

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: setup swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.0"
          
      - name: Get swift version
        run: swift --version

      - name: xcode version
        run: xcodebuild -version

      - name: Clear derived data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Tests
        run: xcodebuild test -project BudgetBook.xcodeproj -scheme BudgetBook -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 16,OS=18.4'
