# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Xcode Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Xcodeのバージョン確認
        run: xcodebuild -version

      - name: シミュレータの一覧（デバッグ用）
        run: xcrun simctl list devices

      - name: ビルド
        run: |
          xcodebuild clean build \
            -workspace YourProject.xcworkspace \  # ← CocoaPods等使っていなければ -project に変えてOK
            -scheme YourSchemeName \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            -sdk iphonesimulator

      - name: テスト
        run: |
          xcodebuild clean test \
            -workspace BudgetBook.xcworkspace \
            -scheme Tests \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            -sdk iphonesimulator \
            -enableCodeCoverage YES
