# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: ビルド & テスト

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: xcode version
        run: xcodebuild -version

      - name: Tests
        run: xcodebuild test -project BudgetBook.xcodeproj -scheme BudgetBook -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 16,OS=18.4'
